# This is a basic workflow to help you get started with Actions

name: Build OpenSSL for macOS (arm64 + Intel)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  version: 1.1.1m
  SHLIB_VERSION_NUMBER: 1.1
  sha256sum: f89199be8b23ca45fc7cb9f1d8d3ee67312318286ad030f5316aca6462db6c96

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download OpenSSL
        run: |
          curl "https://www.openssl.org/source/openssl-${version}.tar.gz" -o openssl-${version}.tar.gz
          echo "${sha256sum}  openssl-${version}.tar.gz" > checksum
          shasum -a 256 -c checksum
          tar xf openssl-${version}.tar.gz
          mkdir universal

      - uses: actions/cache@v3
        id: cache-arm64
        with:
          path: ${GITHUB_WORKSPACE}/openssl-arm64
          key: ${{ runner.os }}-arm64-${{ env.sha256sum }}

      - name: Build OpenSSL on arm64
        if: steps.cache-arm64.outputs.cache-hit != 'true'
        run: |
          cp -r openssl-${version} arm64
          cd arm64
          perl Configure darwin64-arm64-cc no-idea no-mdc2 no-rc5 no-zlib no-ssl3 shared
          make depend
          make all
          make install_sw DESTDIR=${GITHUB_WORKSPACE}/openssl-arm64

      - uses: actions/cache@v3
        id: cache-x86_64
        with:
          path: ${GITHUB_WORKSPACE}/openssl-x86_64
          key: ${{ runner.os }}-arm64-${{ env.sha256sum }}

      - name: Build OpenSSL on x86_64
        if: steps.cache-x86_64.outputs.cache-hit != 'true'
        run: |
          cp -r openssl-${version} x86_64
          cd x86_64
          perl Configure darwin64-x86_64-cc enable-ec_nistp_64_gcc_128 no-idea no-mdc2 no-rc5 no-zlib no-ssl3 shared
          make depend
          make all
          make install_sw DESTDIR=${GITHUB_WORKSPACE}/openssl-x86_64

      - name: Create fat binary
        run: |
          mkdir -p universal/lib
          lipo -create -output universal/lib/libssl.1.1.dylib openssl-arm64/usr/local/lib/libssl.1.1.dylib openssl-x86_64/usr/local/lib/libssl.1.1.dylib
          lipo -create -output universal/lib/libcrypto.1.1.dylib openssl-arm64/usr/local/lib/libcrypto.1.1.dylib openssl-x86_64/usr/local/lib/libcrypto.1.1.dylib
          ln -s libssl.1.1.dylib universal/lib/libssl.dylib
          ln -s libcrypto.1.1.dylib universal/lib/libcrypto.dylib
          cp -r openssl-arm64/usr/local/include/ universal/include/
          tar czf openssl-univeral.tar.gz -C universal .

      - uses: actions/upload-artifact@v3
        with:
          name: openssl-univeral.tar.gz
          path: openssl-univeral.tar.gz
