# This is a basic workflow to help you get started with Actions

name: Build OpenSSL for macOS (arm64 + Intel)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download OpenSSL
        run: curl "https://www.openssl.org/source/openssl-1.1.1m.tar.gz" -o openssl-1.1.1m.tar.gz
