# This is a basic workflow to help you get started with Actions

name: Build OpenSSL for macOS (arm64 + Intel)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download OpenSSL
        run: |
          curl "https://www.openssl.org/source/openssl-1.1.1m.tar.gz" -o openssl-1.1.1m.tar.gz
          tar xf openssl-1.1.1m.tar.gz
          mkdir universal
          cp -r openssl-1.1.1m arm64
          cp -r openssl-1.1.1m x86_64
          
      - name: Build OpenSSL on arm64
        run: |
          cp -r openssl-1.1.1m arm64
          cd arm64
          perl Configure darwin64-arm64-cc no-idea no-mdc2 no-rc5 no-zlib no-ssl3 shared
          make depend
          make all
          make install_sw DESTDIR=${GITHUB_WORKSPACE}/openssl-arm64
          
      - name: Build OpenSSL on x86_64
        run: |
          cp -r openssl-1.1.1m x86_64
          cd x86_64
          perl Configure darwin64-x86_64-cc enable-ec_nistp_64_gcc_128 no-idea no-mdc2 no-rc5 no-zlib no-ssl3 shared
          make depend
          make all
          make install_sw DESTDIR=${GITHUB_WORKSPACE}/openssl-x86_64
      
      - name: Create fat binary
        run: |
          mkdir -p universal/lib
          lipo -create -output universal/lib/libssl.1.1.dylib openssl-arm64/usr/local/lib/libssl.1.1.dylib openssl-x86_64/usr/local/lib/libssl.1.1.dylib
          lipo -create -output universal/lib/libcrypto.1.1.dylib openssl-arm64/usr/local/lib/libcrypto.1.1.dylib openssl-x86_64/usr/local/lib/libcrypto.1.1.dylib
          cp -r openssl-arm64/usr/local/include/ universal/include/
          tar czf openssl-1.1.1m-univeral.tar.gz -C universal .
      
      - uses: actions/upload-artifact@v3
        with:
          name: openssl-1.1.1m-univeral.tar.gz
          path: openssl-1.1.1m-univeral.tar.gz


      
      
          
          
      
